/**
 * Dicionário Universal de Rotas da RevHackers Growth Hub.
 * Este arquivo foi mapeado ESTRITAMENTE a partir das rotas reais do App.tsx.
 * Objetivo: Evitar hardcoding de strings soltas, erros de digitação de URL (404)
 * e facilitar qualquer migração futura de rotas.
 *
 * NOTA DE SEGURANÇA: Não adicione rotas "ideais" aqui se elas não existirem no App.tsx.
 */

export const APP_ROUTES = {
  PUBLIC: {
    HOME: '/',
    PUBLIC_DEAL_ROOM: '/p/:slug',
    BLOG: '/blog',
    BLOG_POST: '/blog/:slug',
    DIAGNOSTICO: '/diagnostico',
    PUBLIC_DIAGNOSTIC_RESULT: '/diagnostico/resultado/:id',
    QUEM_SOMOS: '/quem-somos',
    SERVICOS: '/servicos',
    SERVICOS_DETALHE: '/servicos/:slug',
    METODOLOGIA: '/metodologia',
    CASES: '/cases',
    CASES_DETALHE: '/cases/:slug',
    PARTNER_DETAIL: '/partners/:slug',
    PARTNER_ENICS: '/partners/enics',
    DOWNLOADS: '/downloads',
    MATERIAIS: '/materiais',
    MATERIAL_LANDING: '/materiais/:slug',
    COMUNIDADE: '/comunidade',
    BOOKING: '/booking',
    AGENDA: '/agenda',
    AGENDA_DIAGNOSTICO: '/agenda-diagnostico',
    SUPABASE_DIAGNOSTIC: '/supabase-diagnostic',
    CLIENT_ONBOARDING: '/cadastro-cliente',
    ONBOARDING_SUCCESS: '/onboarding/success',
    MATERIAL_UPLOAD: '/upload-materiais/:projectId',
  },
  LEGAL_AND_FEEDBACK: {
    TERMOS_DE_USO: '/termos-de-uso',
    PRIVACIDADE: '/privacidade',
    THANK_YOU: '/obrigado',
    PESQUISA_NPS: '/pesquisa-nps',
    OBRIGADO_NPS: '/obrigado-nps',
  },
  SPECIALIZED: {
    AGENDA_GIULLIANO_SECURE: '/agenda/giulliano',
    AGENDA_GIULLIANO: '/agenda-giulliano',
    AGENDA_LUNA: '/agenda-luna',
    AGENDA_LINKEDIN: '/agenda-linkedin',
    AGENDA_KICKOFF: '/agenda-kickoff',
    CADASTRO_PARCEIRO: '/cadastro-parceiro',
  },
  SCORES: {
    GROWTH_SCORE: '/score',
    SITE_SCORE: '/score-site',
    FOUNDER_SCORE: '/score-founder',
    REVENUE_SCORE: '/score-revenue',
  },
  REI: {
    HUB_REDIRECT: '/rei',
    HUB: '/rei-hub',
    WIZARD: '/rei/wizard',
    RESULT: '/rei/resultado/:id',
    SUCCESS: '/rei/success',
    DEV: '/rei-dev',
    CONSULTING: '/rei-consulting',
    FOUNDER: '/rei-founder',
    LEGACY_ONBOARDING: '/rei-onboarding',
    LEGACY_DASHBOARD: '/rei-dashboard',
  },
  AUTH: {
    LOGIN: '/login',
    SIGNUP: '/signup',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    COMPLETE_PROFILE: '/complete-profile',
  },
  ADMIN: {
    ROOT_REDIRECT: '/admin',
    DASHBOARD: '/admin/dashboard',
    GLOBAL_DASHBOARD: '/dashboard', // App.tsx redirects /dashboard -> /admin
    REI_PROJECTS: '/admin/rei',
    REI_PROJECT_NEW: '/admin/rei/novo',
    REI_PROJECT_EDIT: '/admin/rei/:id',
    ORCHESTRATED_ONBOARDING: '/admin/jornada/:id',
    STRATEGIC_PLAN: '/admin/strategic-plan/:projectId',
    RESULTS_REPORT: '/admin/resultados/:projectId',
    PROFILE: '/admin/profile',
    USERS: '/admin/users',
    SETTINGS: '/admin/settings',
    CLIENTS: '/admin/clients',
    CLIENT_NEW: '/admin/clients/novo',
    CLIENT_EDIT: '/admin/clients/edit/:id',
    POSTS: '/admin/posts',
    POST_NEW: '/admin/posts/new',
    POST_EDIT: '/admin/posts/edit/:id',
    MATERIALS: '/admin/materials',
    MATERIAL_NEW: '/admin/materials/new',
    MATERIAL_EDIT: '/admin/materials/edit/:id',
    FIX_MATERIALS: '/admin/fix-materials',
    CASES: '/admin/cases',
    CASE_NEW: '/admin/cases/new',
    CASE_EDIT: '/admin/cases/edit/:id',
    SYNC: '/admin/sync',
    ESTRATEGIA: '/admin/estrategia',
    ESTRATEGIA_EDIT: '/admin/estrategia/:id',
    CRONOGRAMA: '/admin/cronograma',
    CRONOGRAMA_EDIT: '/admin/cronograma/:id',
    PROJECT_DETAILS: '/admin/projects/:id',
    DIAGNOSTIC_VIEW: '/admin/diagnostico/:id',
    STRATEGIC_PLAN_GENERATOR: '/admin/planejamento/:reiProjectId',
    INTEGRATIONS: '/admin/integrations',
    PROPOSALS: '/admin/proposals',
    PROPOSAL_NEW: '/admin/proposals/new',
    PROPOSAL_EDIT: '/admin/proposals/edit/:id',
  },
  CLIENT_HUB: {
    STRATEGIC_PLAN_PRESENTATION: '/plan/:token',
    PLAN_SIGN: '/plan/:token/sign',
    HUB: '/hub/:id',
  }
} as const;
