-- Create proposals table
create table "public"."proposals" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "title" text not null,
    "slug" text not null,
    "client_name" text not null,
    "client_logo" text, -- URL to image
    "recording_url" text, -- Loom/Youtube embed URL
    "transcript" text, -- Raw text for AI processing
    "mindmap_code" text, -- Mermaid.js code generated by AI
    "summary" text, -- AI generated executive summary
    "scope" jsonb default '[]'::jsonb, -- Array of deliverables { title, description, price? }
    "investment_total" numeric,
    "status" text default 'draft', -- draft, sent, approved, rejected
    "access_token" text default md5(random()::text), -- Simple token for public access without login
    "user_id" uuid references auth.users(id)
);

-- Indexes
create unique index proposals_slug_key on "public"."proposals" using btree ("slug");

-- RLS
alter table "public"."proposals" enable row level security;

create policy "Enable read access for public with token"
on "public"."proposals"
as permissive
for select
to public
using ( true ); -- We will handle token check in the application logic or use valid slug + token combo query

create policy "Enable all access for authenticated users"
on "public"."proposals"
as permissive
for all
to authenticated
using ( true )
with check ( true );

-- Add trigger for updated_at
create trigger handle_updated_at before update on proposals
  for each row execute procedure moddatetime (updated_at);
